name: 'Analyze'

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  analyze:
    runs-on: 'ubuntu-latest'

    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']

    steps:
      - uses: 'actions/checkout@v2.3.4'

      - name: 'Initialize CodeQL'
        uses: 'github/codeql-action/init@v1'
        with:
          languages: ${{ matrix.language }}

      - name: 'Perform CodeQL Analysis'
        uses: 'github/codeql-action/analyze@v1'
