name: 'Test'

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  test:
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: 'actions/checkout@v2.3.4'

      - name: 'Use Node.js'
        uses: 'actions/setup-node@v2.1.5'
        with:
          node-version: '14.x'

      - name: 'Cache dependencies'
        uses: 'actions/cache@v2.1.6'
        with:
          path: '.npm'
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: 'Install'
        run: 'npm ci --cache .npm --prefer-offline'

      - name: 'Test'
        run: 'npm run test'
