name: 'Test'

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  test-unit:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2.4.0'

      - name: 'Use Node.js'
        uses: 'actions/setup-node@v2.4.1'
        with:
          node-version: '16.x'
          cache: 'npm'

      - name: 'Install'
        run: 'npm install'

      - name: 'Unit Test'
        run: 'npm run test:unit'

  test-e2e-docker:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2.4.0'

      - name: 'Use Docker'
        uses: 'actions-hub/docker/cli@master'
        env:
          SKIP_LOGIN: true

      - name: 'Use Node.js'
        uses: 'actions/setup-node@v2.4.1'
        with:
          node-version: '16.x'
          cache: 'npm'

      - name: 'Install'
        run: 'npm install'

      - name: 'Build'
        run: 'npm run build'

      - name: 'Install leon'
        run: 'npm install --global'

      - name: 'End To End (e2e) Test with Docker'
        run: 'npm run test:e2e-docker'
